### ISSUE TITLE
about ffprobe

### ISSUE THREAD

**Issue by bberzh** [ecsplendid/rembg#6]
hello, I encountered an error while running，could you help me?
(torchenv) zjy@sugon-X795-G30:~/rembg-greenscreen-master$ greenscreen -pg "/public/zjy/rembg-greenscreen-master/vid/1.mp4"
/public/zjy/rembg-greenscreen-master/vid/1.mp4
Traceback (most recent call last):
  File "/public/zjy/.local/bin/greenscreen", line 8, in <module>
    sys.exit(main())
  File "/public/zjy/.local/lib/python3.8/site-packages/rembg/cmd/cli.py", line 77, in main
    parallel_greenscreen(os.path.abspath(args.parallelgreenscreen),
  File "/public/zjy/.local/lib/python3.8/site-packages/rembg/multiprocessing.py", line 75, in parallel_greenscreen
    info = ffmpeg.probe(file_path)
  File "/public/zjy/.local/lib/python3.8/site-packages/ffmpeg/_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/public/lzh/anaconda3/envs/torchenv/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/public/lzh/anaconda3/envs/torchenv/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'

**Comment by Oppfields** [comment]
I get the same error on macOS Big Sur and I suspect your issue relates to strict versioning on the dependencies (requirements.txt). Specifically scikit_image==0.17.2. I would recommend testing [danielgatis/rembg](https://github.com/danielgatis/rembg) first then report back to here if it works. @ecsplendid is aware of the issue and I believe he's trying to find time to test rembg-greenscreen on macOS.

rembg – Remove the background from all images in a folder
[danielgatis/rembg](https://github.com/danielgatis/rembg)

~% rembg -p path/to/input path/to/output

1. export the frames to a directory
2. batch process to remove the background
3. recreate the movie using the processed frames

**Comment by SandUhrGucker** [comment]
> No such file or directory: 'ffprobe'

Did you install ffmpeg?

**Comment by chen849157649** [comment]
sudo apt-get install ffmpeg
